name: AssettoServer [ GameServer ] - Build and Push

# This workflow builds and pushes the main game server container image
# The game server container runs the actual Assetto Corsa server process
#
# Triggers:
# - Tags only (v*)
# Environment is determined by the branch where the tag is created:
# - master branch -> prod
# - staging branch -> staging

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        if: ${{ github.ref_base_ref != 'refs/heads/dev' }}
        environment: ${{ github.ref_base_ref == 'refs/heads/master' && 'prod' || 'staging' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set image tag suffix
              id: tag_suffix
              run: |
                  ENV="${{ github.ref_base_ref == 'refs/heads/master' && 'prod' || 'staging' }}"
                  echo "suffix=.$ENV" >> $GITHUB_OUTPUT

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      ewr.vultrcr.com/corsaclub/docker/assetto_corsa-server${{ steps.tag_suffix.outputs.suffix }}
                  tags: |
                      type=raw,value={{tag}}
                      type=sha,format=long

            - name: Login to Vultr Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ewr.vultrcr.com
                  username: ${{ secrets.VULTR_REGISTRY_USERNAME }}
                  password: ${{ secrets.VULTR_REGISTRY_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./docker/Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      STEAM_USERNAME=${{ secrets.STEAM_USERNAME }}
                      STEAM_PASSWORD=${{ secrets.STEAM_PASSWORD }}

