name: Docker
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ewr.vultrcr.com/corsaclub/assettoserver
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Vultr Container Registry
        uses: docker/login-action@v2
        with:
          registry: ewr.vultrcr.com
          username: ${{ secrets.VULTR_REGISTRY_USERNAME }}
          password: ${{ secrets.VULTR_REGISTRY_TOKEN }}

      - name: Build the Image
        run: |
          docker buildx bake -f docker/bake.hcl -f ${{ steps.meta.outputs.bake-file }} --push
