name: AssettoServer GameServer - Build and Push

# This workflow builds and pushes the main game server container image
# The game server container runs the actual Assetto Corsa server process
#
# Triggers:
# - Manual dispatch with environment selection
# - Tags
# - Push to relevant paths
#
# Environments:
# - dev: For development and testing
# - staging: For staging deployment
# - prod: For production deployment

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy to"
                required: true
                default: "staging"
                type: choice
                options:
                    - dev
                    - staging
                    - prod
    push:
        tags:
            - "v*"
        paths:
            - "**"
            - ".github/workflows/docker.yaml"

jobs:
    build:
        if: |
            github.event_name == 'workflow_dispatch' ||
            contains(github.ref, 'refs/tags/')
        name: Build Docker Image
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment || (github.base_ref == 'main' && 'prod') || 'staging' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set image tag suffix
              id: tag_suffix
              run: |
                  # Determine environment based on base branch for tags
                  if [[ $GITHUB_REF == refs/tags/* ]]; then
                    BASE_BRANCH=$(git branch -r --contains $GITHUB_REF | grep -E 'origin/(main|master)' || echo "")
                    if [[ ! -z "$BASE_BRANCH" ]]; then
                      ENV="prod"
                    else
                      ENV="staging"
                    fi
                  else
                    ENV="${{ github.event.inputs.environment || 'staging' }}"
                  fi
                  echo "suffix=.$ENV" >> $GITHUB_OUTPUT

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ewr.vultrcr.com/corsaclub/docker/assetto_corsa-server${{ steps.tag_suffix.outputs.suffix }}
                  tags: |
                      type=ref,event=tag
                      type=sha,format=long
                  labels: |
                      org.opencontainers.image.title=AssettoServer GameServer
                      org.opencontainers.image.description=Main Assetto Corsa server process
                      maintainer=CorsaClub

            - name: Login to Vultr Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ewr.vultrcr.com
                  username: ${{ secrets.VULTR_REGISTRY_USERNAME }}
                  password: ${{ secrets.VULTR_REGISTRY_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./docker/Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

