name: Build
on:
  push:
    tags:
      - "v*"

# Ajout des permissions nécessaires
permissions:
  contents: write # Permission pour créer des releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Publish (Linux x64)
        run: dotnet publish --runtime linux-x64 -c Release
      - name: Publish (Linux arm64)
        run: dotnet publish --runtime linux-arm64 -c Release
      - name: Publish (Windows x64)
        run: dotnet publish --runtime win-x64 -c Release
      - name: Package (Linux x64)
        run: cd out-linux-x64 && tar -czf assetto-server-linux-x64.tar.gz * && cd ..
      - name: Package (Linux arm64)
        run: cd out-linux-arm64 && tar -czf assetto-server-linux-arm64.tar.gz * && cd ..
      - name: Package (Windows x64)
        run: cd out-win-x64 && zip -r assetto-server-win-x64.zip * && cd ..
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          prerelease: true
          repository: ${{ github.repository }}
          files: |
            out-linux-x64/assetto-server-linux-x64.tar.gz
            out-linux-arm64/assetto-server-linux-arm64.tar.gz
            out-win-x64/assetto-server-win-x64.zip
